name: 'yarn prepare'
description: ''
runs:
  using: 'composite'
  steps:
    # reference .node-version file to set node version
    - name: Set node version
      run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV
      shell: bash
    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: corepack enable
      shell: bash
    # Corepack有効後でないとyarn cacheを動作させられないため、setup-nodeを2回実行している
    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
      shell: bash
