name: 'yarn prepare'
description: ''
runs:
  using: 'composite'
  steps:
    # reference .node-version file to set node version
    - name: Set node version
      run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: corepack enable
      shell: bash
    # Corepack有効後でないとyarn cacheを動作させられないため、setup-nodeを2回実行している
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
      shell: bash
