import { Breadcrumbs } from '@/components/molecules/Breadcrumbs';
import { Post } from '@/types/entry';
import { GetStaticPaths, GetStaticProps, NextPage } from 'next';
import React, { useMemo } from 'react';
import { PostIndexItem } from '../../src/types/postIndex';
import { generatePostBreadcrumbsList } from '../../src/libs/breadcrumbsGenerator';
import { PostArea } from '@/components/organisms/PostArea';
import Head from 'next/head';
import Script from 'next/script';
import { POSTS_LIMIT } from '@/libs/const';
import { Posts } from '@/components/organisms/Posts';
import { PostPagination } from '@/components/organisms/PostPagination';

interface Props {
  posts: Post[];
  page: number;
  count: number;
}

export const getStaticPaths: GetStaticPaths<{ page: string }> = async () => {
  const { fetchAllPost } = await import('@/libs/contentful');

  const posts = await fetchAllPost();
  const allPage = Math.ceil(posts.items.length / POSTS_LIMIT);

  return {
    paths: Array(allPage)
      .fill(undefined)
      .map((_, page) => ({
        params: {
          page: (page + 1).toString(),
        },
      })),
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps<Props> = async (context) => {
  const { fetchPosts, fetchPostsCount } = await import('@/libs/contentful');
  if (!context.params || !context.params.page || context.params.page === '') {
    return {
      notFound: true,
    };
  }
  const page = Number(context.params.page);
  const limit = POSTS_LIMIT;

  const posts = await fetchPosts(page - 1, limit).then((posts) => {
    return posts.items.map((item) => {
      item.fields.body = '';
      return item;
    });
  });

  const count = await fetchPostsCount();

  return {
    props: {
      page,
      posts,
      count,
    },
  };
};

const Page: NextPage<Props> = ({ count, page, posts }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostPagination
        baseUrl="/page"
        currentPage={page}
        limit={POSTS_LIMIT}
        postsCount={count}
      />
      <Posts posts={posts} />
    </>
  );
};

export default Page;
