name: Check Markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/workflows/mlc_config.json'
          folder-path: '_data/_posts'
