name: Check Markdown links

on:
  push:
    paths:
      - '_data/_posts/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/workflows/mlc_config.json'
          folder-path: '_data/_posts'
