name: textlint
on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - '_data/_posts/**'
jobs:
  textlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn-prepare
      - run: yarn lint:post >> ./.textlint.log
      - name: put textlint result
        if: failure()
        run: gh pr comment --body-file ./.textlint.log "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
